name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TOOL_CHAIN: gmake2
  BUILD_CONFIGURATION: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup premake
      uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"
    
    - name: Run premake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        premake5 ${{env.TOOL_CHAIN}}
        
    - name: Libraries and headers
      run: |
        sudo apt-get update
        sudo apt install xorg-dev
        sudo apt install gcc-11 g++-11
        
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
        
    - name: Make
      working-directory: ${{env.TOOL_CHAIN}}
      env:
        CC: gcc-11
        CXX: g++-11
      run: |
        make config=release
